---
sudo: required
language: python

services:
  - docker

python: "2.7"

cache: pip

virtualenv:
  system_site_packages: false

install:
- pip install --upgrade setuptools
- pip install ome-ansible-molecule/

script:
- cd $ROLE && ../scripts/test.sh

env:
 - ROLE=ansible-role-basedeps
 - ROLE=ansible-role-deploy-archive
 - ROLE=ansible-role-haproxy
 - ROLE=ansible-role-ice
 - ROLE=ansible-role-java
 - ROLE=ansible-role-nginx-proxy
 - ROLE=ansible-role-nginx
 - ROLE=ansible-role-omego
 - ROLE=ansible-role-omero-common
 - ROLE=ansible-role-omero-python-deps
 - ROLE=ansible-role-postgresql
 - ROLE=ansible-role-python-pydata
 - ROLE=ansible-role-ssl-certificate
 - ROLE=ansible-role-versioncontrol-utils
